import { createApp } from 'vue'
// import App from './App01-cesium基础.vue'
// import App from './App02-设置天空盒子.vue'
// import App from './App03-viewer设置地形.vue'
// import App from './App04-坐标系和相机设置.vue'
// import App from './App05-控制相机运动.vue'
// import App from './App06-加载本地地形数据.vue'
// import App from './App07-地图添加与叠加地图.vue'
// import App from './App08-添加全球城市建筑物.vue'
// import App from './App10-加载飞机模型.vue'
// import App from './App12-多边形和折线.vue'
// import App from './App15-广告牌标签.vue'
import App from './App18-primitive.vue'
// import App from './App.vue'

createApp(App).mount('#app')
